### ISSUE TITLE
LM Studio Support

### ISSUE THREAD

**Issue by MedTaha4Ever** [Isulion/ComfyUI_Isulion#3]
will LM Studio have Support in the future ?

**Comment by Isulion** [comment]
You can use already existing custom node, like [LM Studio Image to Text Node for ComfyUI](https://github.com/mattjohnpowell/comfyui-lmstudio-image-to-text-node)

This is an example Workflow for you :
![workflow](https://github.com/user-attachments/assets/78974b76-c09a-4d24-943f-d2497b5b786d)
