### ISSUE TITLE
在新的COMFYUI桌面测试版中不能正常工作

### ISSUE THREAD

**Issue by ai201414** [Isulion/ComfyUI_Isulion#4]
正常通过MANAGER安装，但不能生成提示词。

**Comment by Isulion** [comment]
Have you tried with the Mega Prompt Generator ?
Here is a simple example :
![image](https://github.com/user-attachments/assets/fd312070-6138-4f01-88b3-5105acdc5aca)

Can you confirm that it works ?

**Comment by ai201414** [comment]
我就是这样测试的，没有生成任何提示词。仅仅在桌面测试版里这样。
![屏幕截图 2024-11-10 231315](https://github.com/user-attachments/assets/7e62337b-ae12-468e-af2a-0e681126d318)

**Comment by Isulion** [comment]
Can you update please ? and try again ?
Have you any errors in console that you can show here ?

**Comment by ai201414** [comment]
已经更新了，还是一样，控制台没有报错

**Comment by Isulion** [comment]
That's really surprising, as I've tested it on different configurations and you're the first one to encounter the problem... Maybe it's a conflict with another node? Could you try installing the node on a fresh install of ComfyUI? To check if it's coming from ComfyUI or your machine?

这真让人惊讶，我在不同的配置上测试过，你是第一个遇到这个问题的……可能是与另一个节点的冲突？你能尝试在全新安装的 ComfyUI 上安装该节点吗？以检查问题是否来自 ComfyUI 或你的机器？

**Comment by ai201414** [comment]
不知道是不是我的中文表达让你误解。我只是在COMFYUI还没有正式推出的桌面测试版中才出现这样的问题。正常的COMFYUI版本是没有问题的。

I don't know if my Chinese expression caused you to misunderstand. I only encountered this issue in the desktop beta version of COMFYUI that has not yet been officially released. The normal COMFYUI version is fine.

**Comment by Isulion** [comment]
Thank you for this precision! I misunderstood it. 
I will test this version as soon as possible and correct any bug. I will keep you informed, for sure.

感谢您的说明！我误解了。我会尽快测试这个版本，并修正任何错误。我一定会通知您的。

**Comment by Isulion** [comment]
Hello/你好 @ai201414,

Could you test something like this ?

你能测试一下这个吗？

![image](https://github.com/user-attachments/assets/0b8fea41-2e46-4336-9e1d-cd5167c81af1)

**Comment by ai201414** [comment]
测试了您给出的工作节点，现在终端有错误信息了。
I have tested the work node you provided, and now there is an error message on the terminal.
 WARNING: 'bool' object is not callable

**Comment by Isulion** [comment]
> 测试了您给出的工作节点，现在终端有错误信息了。 I have tested the work node you provided, and now there is an error message on the terminal. WARNING: 'bool' object is not callable

你可以试试 v2！/ You may try the v2 !
